### ISSUE TITLE
Change the Promise type to Awaited

### ISSUE THREAD

**Issue by meech-ward** [meech-ward/might-fail#17]
@iliaamiri Can you take a look at this? the solution is at the bottom

```ts
function someResponse() {
  const responses = [
    { status: 200, data: { id: 1, name: "John Doe" }, json: async () => ({ status: 200, data: { id: 1, name: "John Doe" } }) },
    { status: 404, error: "Not Found", json: async () => ({ status: 404, error: "Not Found" }) },
    { status: 500, error: "Internal Server Error", json: async () => ({ status: 500, error: "Internal Server Error" }) },
    { status: 201, data: { id: 2, name: "Jane Smith", created: true }, json: async () => ({ status: 201, data: { id: 2, name: "Jane Smith", created: true } }) },
    { status: 400, error: "Bad Request", details: ["Invalid email", "Password too short"], json: async () => ({ status: 400, error: "Bad Request", details: ["Invalid email", "Password too short"] }) },
  ];

  const randomIndex = Math.floor(Math.random() * responses.length);
  const randomResponse = responses[randomIndex];

  return randomResponse;
}

async function main2() {
  const res = someResponse()
  const [error, result] = await mightFail(res.json())
  if (error) {
    console.error(error)
    return
  }
}
```

at ` const [error, result] = await mightFail(res.json())`, i get this ts error:

```
Argument of type 'Promise<{ status: number; error: string; }> | Promise<{ status: number; data: { id: number; name: string; }; }>' is not assignable to parameter of type 'Promise<{ status: number; error: string; }>'.
  Type 'Promise<{ status: number; data: { id: number; name: string; }; }>' is not assignable to type 'Promise<{ status: number; error: string; }>'.
    Property 'error' is missing in type '{ status: number; data: { id: number; name: string; }; }' but required in type '{ status: number; error: string; }'.ts(2345)
```

Because the function returns potentially many different promises instead of a single promise with different values. It's kind of a stupid edge case here but I found it when dealing with some rpc calls in hono where the function can return different json responses depending on the status code.

Anyway, I can solve it by changing the `MightFailFunction` type in utils.type.ts

from this:

```ts
export type MightFailFunction<TEitherMode extends EitherMode> = <T>(
  promise: Promise<T>
) => Promise<
  TEitherMode extends "standard"
    ? StandardEither<T>
    : TEitherMode extends "go"
    ? GoEither<T>
    : AnyEither<T>
>
```

to this:

```ts
export type MightFailFunction<TEitherMode extends EitherMode> = <T>(
  promise: T
) => Promise<
  TEitherMode extends "standard"
    ? StandardEither<Awaited<T>>
    : TEitherMode extends "go"
    ? GoEither<Awaited<T>>
    : AnyEither<Awaited<T>>
>
```

So that's the fix, done.

Except, @iliaamiri has done some good work and done a bunch of TS stuff I don't fully understand. Can you check if this change make sense to apply to the other types?

**Comment by iliaamiri** [comment]
@meech-ward Oh, yeah it's interesting because it's in the array, each item gets a union type. I think the only reason it works in this case is because the two types can get merged together properly by TypeScript. The `Promise` was preventing them to merge together. 

I can't think of a better solution than this. And, I don't think that would cause any issues either since the Either type will be awaited anyway (because we always pass a promise to the `MightFailFunction`. 

![image](https://github.com/user-attachments/assets/b9cccf7a-1c81-439d-9422-d363de3312c3)

The only other places I find this rule applies is in the Static Methods, which interestingly already have this `Awaited` type applied to them.

![image](https://github.com/user-attachments/assets/641f8d3b-cbac-440f-921d-4ceaa89ae6a0)

Oh also, we literally copy pasted the types from the EcmaScript references, so that kind of makes me think this is probably the best choice.

**Comment by meech-ward** [comment]
Ok I couldn't remember where we got this code from. So basically we should probably just use this style?

```ts
export interface PromiseStaticMethods<TEitherMode extends EitherMode> {
  /**
   * Wraps a Promise.all call in a mightFail function.
   * @param values - An iterable of promises
   * @template T The type of the resolved values
   * @return {Promise} - Promise<Awaited<Either<T[]>>>
   */
  all<T>(
    values: Iterable<T | PromiseLike<T>>
  ): Promise<
    TEitherMode extends "standard"
      ? Awaited<StandardEither<T[]>>
      : TEitherMode extends "go"
      ? Awaited<GoEither<T[]>>
      : Awaited<AnyEither<T[]>>
  >
  ```
  
  Where the promise is `PromiseLike` and we accept `T` or `PromiseLike<T>` and return `Awaited<Either>` instead of `Either<Awaited>`

**Comment by iliaamiri** [comment]
Hmm, to be honest, I'm not sure at all. We literally copy pasted those from the Promise method codebases. They had it as `Awaited<T>` so we made it `Awaited<Either<T[]>`. Not sure what difference does it make to have it as `Either<Awaited<T>>`

**Comment by meech-ward** [comment]
https://github.com/meech-ward/might-fail/pull/18
